Repository syphon-lang/syphon, pull requests merged in 2024-07, with the labels that each got.

#24 Make a Thread Safety approach (Global Interpreter Lock)
  src/vm/VirtualMachine.zig
  src/vm/builtins/Threading.zig
Labels: enhancement

#26 Make the Shell Module
  docs/builtins/shell.md
  src/vm/builtins/Module.zig
  src/vm/builtins/Shell.zig
Labels: enhancement

#30 The optimizations we need and deserve
  src/Driver.zig
  src/compiler/CodeGen.zig
  src/ds/hash_map_recorder.zig
  src/vm/Atom.zig
  src/vm/Code.zig
  src/vm/VirtualMachine.zig
  src/vm/builtins/Array.zig
  src/vm/builtins/Console.zig
  src/vm/builtins/Hash.zig
  src/vm/builtins/Map.zig
  src/vm/builtins/Module.zig
  src/vm/builtins/Process.zig
  src/vm/builtins/Random.zig
  src/vm/builtins/String.zig
  src/vm/builtins/Threading.zig
  src/vm/builtins/Type.zig
  tests/benchmarks/arithmetic.sy
  tests/benchmarks/loop.sy
Labels: enhancement, optimization

#31 Add a `version` command
  build.zig
  src/Driver.zig
Labels: enhancement

#33 Make a Foreign Function Interface module
  build.zig
  build.zig.zon
  docs/builtins/ffi.md
  src/vm/Code.zig
  src/vm/builtins/ForeignFunctionInterface.zig
  src/vm/builtins/Module.zig
Labels: enhancement

#37 feat: replace `map_foreach` function with `foreach` for iterating through iterables (array, map, string)
  src/vm/Code.zig
  src/vm/builtins/Array.zig
  src/vm/builtins/Map.zig
Labels: enhancement

#38 docs: explain the `foreach` function
  docs/builtins/global.md
Labels: documentation

#39 style: internal function naming to be camelCase like Zig's standard library
  src/vm/builtins/Array.zig
  src/vm/builtins/Map.zig
Labels: style

#51 feat: let the compiler handle local variables
  src/Driver.zig
  src/compiler/CodeGen.zig
  src/ds/hash_map_recorder.zig
  src/vm/Code.zig
  src/vm/VirtualMachine.zig
  src/vm/builtins/Module.zig
  src/vm/builtins/Threading.zig
  tests/integration/tester.sy
Labels: enhancement, optimization
